### ISSUE TITLE
Add tooltip dropdown library

### ISSUE THREAD

**Issue by dqsmith** [dqsmith/planning-poker-kit#3]
Add tooltip dropdown library

- All navigation buttons and icons should have a sleek tooltop drop down (versus the browser hover)
- Drop down/popup should be unobtrusive but immediately available as a help hint or clue

**Comment by arijose** [comment]
We use ng2-popover in Cayman for validation error pop ups. What do you think about that?

**Comment by dqsmith** [comment]
Sounds good!

**Comment by arijose** [comment]
I may have missed a button. Hit me up if I did and I'll add it.
